//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7Task3.TweetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tweet", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tweet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PostIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryField;
        
        private System.DateTime DatePostedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PostId {
            get {
                return this.PostIdField;
            }
            set {
                if ((this.PostIdField.Equals(value) != true)) {
                    this.PostIdField = value;
                    this.RaisePropertyChanged("PostId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Entry {
            get {
                return this.EntryField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryField, value) != true)) {
                    this.EntryField = value;
                    this.RaisePropertyChanged("Entry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DatePosted {
            get {
                return this.DatePostedField;
            }
            set {
                if ((this.DatePostedField.Equals(value) != true)) {
                    this.DatePostedField = value;
                    this.RaisePropertyChanged("DatePosted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TweetService.TweetServiceSoap")]
    public interface TweetServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetTweetsBetweenDatesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweetsBetweenDates", ReplyAction="*")]
        Lab7Task3.TweetService.GetTweetsBetweenDatesResponse GetTweetsBetweenDates(Lab7Task3.TweetService.GetTweetsBetweenDatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetTweetsPagedResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweetsPaged", ReplyAction="*")]
        Lab7Task3.TweetService.GetTweetsPagedResponse GetTweetsPaged(Lab7Task3.TweetService.GetTweetsPagedRequest request);
        
        // CODEGEN: Generating message contract since element name GetLast100TweetsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLast100Tweets", ReplyAction="*")]
        Lab7Task3.TweetService.GetLast100TweetsResponse GetLast100Tweets(Lab7Task3.TweetService.GetLast100TweetsRequest request);
        
        // CODEGEN: Generating message contract since element name tweet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostTweet", ReplyAction="*")]
        Lab7Task3.TweetService.PostTweetResponse PostTweet(Lab7Task3.TweetService.PostTweetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsBetweenDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsBetweenDates", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetTweetsBetweenDatesRequestBody Body;
        
        public GetTweetsBetweenDatesRequest() {
        }
        
        public GetTweetsBetweenDatesRequest(Lab7Task3.TweetService.GetTweetsBetweenDatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsBetweenDatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime endDate;
        
        public GetTweetsBetweenDatesRequestBody() {
        }
        
        public GetTweetsBetweenDatesRequestBody(System.DateTime startDate, System.DateTime endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsBetweenDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsBetweenDatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetTweetsBetweenDatesResponseBody Body;
        
        public GetTweetsBetweenDatesResponse() {
        }
        
        public GetTweetsBetweenDatesResponse(Lab7Task3.TweetService.GetTweetsBetweenDatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsBetweenDatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7Task3.TweetService.Tweet[] GetTweetsBetweenDatesResult;
        
        public GetTweetsBetweenDatesResponseBody() {
        }
        
        public GetTweetsBetweenDatesResponseBody(Lab7Task3.TweetService.Tweet[] GetTweetsBetweenDatesResult) {
            this.GetTweetsBetweenDatesResult = GetTweetsBetweenDatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsPagedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsPaged", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetTweetsPagedRequestBody Body;
        
        public GetTweetsPagedRequest() {
        }
        
        public GetTweetsPagedRequest(Lab7Task3.TweetService.GetTweetsPagedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsPagedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int page;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int number;
        
        public GetTweetsPagedRequestBody() {
        }
        
        public GetTweetsPagedRequestBody(int page, int number) {
            this.page = page;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsPagedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsPagedResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetTweetsPagedResponseBody Body;
        
        public GetTweetsPagedResponse() {
        }
        
        public GetTweetsPagedResponse(Lab7Task3.TweetService.GetTweetsPagedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsPagedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7Task3.TweetService.Tweet[] GetTweetsPagedResult;
        
        public GetTweetsPagedResponseBody() {
        }
        
        public GetTweetsPagedResponseBody(Lab7Task3.TweetService.Tweet[] GetTweetsPagedResult) {
            this.GetTweetsPagedResult = GetTweetsPagedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLast100TweetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLast100Tweets", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetLast100TweetsRequestBody Body;
        
        public GetLast100TweetsRequest() {
        }
        
        public GetLast100TweetsRequest(Lab7Task3.TweetService.GetLast100TweetsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLast100TweetsRequestBody {
        
        public GetLast100TweetsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLast100TweetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLast100TweetsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.GetLast100TweetsResponseBody Body;
        
        public GetLast100TweetsResponse() {
        }
        
        public GetLast100TweetsResponse(Lab7Task3.TweetService.GetLast100TweetsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLast100TweetsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7Task3.TweetService.Tweet[] GetLast100TweetsResult;
        
        public GetLast100TweetsResponseBody() {
        }
        
        public GetLast100TweetsResponseBody(Lab7Task3.TweetService.Tweet[] GetLast100TweetsResult) {
            this.GetLast100TweetsResult = GetLast100TweetsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostTweetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostTweet", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.PostTweetRequestBody Body;
        
        public PostTweetRequest() {
        }
        
        public PostTweetRequest(Lab7Task3.TweetService.PostTweetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostTweetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7Task3.TweetService.Tweet tweet;
        
        public PostTweetRequestBody() {
        }
        
        public PostTweetRequestBody(Lab7Task3.TweetService.Tweet tweet) {
            this.tweet = tweet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostTweetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostTweetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7Task3.TweetService.PostTweetResponseBody Body;
        
        public PostTweetResponse() {
        }
        
        public PostTweetResponse(Lab7Task3.TweetService.PostTweetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostTweetResponseBody {
        
        public PostTweetResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TweetServiceSoapChannel : Lab7Task3.TweetService.TweetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TweetServiceSoapClient : System.ServiceModel.ClientBase<Lab7Task3.TweetService.TweetServiceSoap>, Lab7Task3.TweetService.TweetServiceSoap {
        
        public TweetServiceSoapClient() {
        }
        
        public TweetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TweetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7Task3.TweetService.GetTweetsBetweenDatesResponse Lab7Task3.TweetService.TweetServiceSoap.GetTweetsBetweenDates(Lab7Task3.TweetService.GetTweetsBetweenDatesRequest request) {
            return base.Channel.GetTweetsBetweenDates(request);
        }
        
        public Lab7Task3.TweetService.Tweet[] GetTweetsBetweenDates(System.DateTime startDate, System.DateTime endDate) {
            Lab7Task3.TweetService.GetTweetsBetweenDatesRequest inValue = new Lab7Task3.TweetService.GetTweetsBetweenDatesRequest();
            inValue.Body = new Lab7Task3.TweetService.GetTweetsBetweenDatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            Lab7Task3.TweetService.GetTweetsBetweenDatesResponse retVal = ((Lab7Task3.TweetService.TweetServiceSoap)(this)).GetTweetsBetweenDates(inValue);
            return retVal.Body.GetTweetsBetweenDatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7Task3.TweetService.GetTweetsPagedResponse Lab7Task3.TweetService.TweetServiceSoap.GetTweetsPaged(Lab7Task3.TweetService.GetTweetsPagedRequest request) {
            return base.Channel.GetTweetsPaged(request);
        }
        
        public Lab7Task3.TweetService.Tweet[] GetTweetsPaged(int page, int number) {
            Lab7Task3.TweetService.GetTweetsPagedRequest inValue = new Lab7Task3.TweetService.GetTweetsPagedRequest();
            inValue.Body = new Lab7Task3.TweetService.GetTweetsPagedRequestBody();
            inValue.Body.page = page;
            inValue.Body.number = number;
            Lab7Task3.TweetService.GetTweetsPagedResponse retVal = ((Lab7Task3.TweetService.TweetServiceSoap)(this)).GetTweetsPaged(inValue);
            return retVal.Body.GetTweetsPagedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7Task3.TweetService.GetLast100TweetsResponse Lab7Task3.TweetService.TweetServiceSoap.GetLast100Tweets(Lab7Task3.TweetService.GetLast100TweetsRequest request) {
            return base.Channel.GetLast100Tweets(request);
        }
        
        public Lab7Task3.TweetService.Tweet[] GetLast100Tweets() {
            Lab7Task3.TweetService.GetLast100TweetsRequest inValue = new Lab7Task3.TweetService.GetLast100TweetsRequest();
            inValue.Body = new Lab7Task3.TweetService.GetLast100TweetsRequestBody();
            Lab7Task3.TweetService.GetLast100TweetsResponse retVal = ((Lab7Task3.TweetService.TweetServiceSoap)(this)).GetLast100Tweets(inValue);
            return retVal.Body.GetLast100TweetsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7Task3.TweetService.PostTweetResponse Lab7Task3.TweetService.TweetServiceSoap.PostTweet(Lab7Task3.TweetService.PostTweetRequest request) {
            return base.Channel.PostTweet(request);
        }
        
        public void PostTweet(Lab7Task3.TweetService.Tweet tweet) {
            Lab7Task3.TweetService.PostTweetRequest inValue = new Lab7Task3.TweetService.PostTweetRequest();
            inValue.Body = new Lab7Task3.TweetService.PostTweetRequestBody();
            inValue.Body.tweet = tweet;
            Lab7Task3.TweetService.PostTweetResponse retVal = ((Lab7Task3.TweetService.TweetServiceSoap)(this)).PostTweet(inValue);
        }
    }
}
