// <auto-generated />
namespace CST8359_Assignment2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CommentCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131706550_Comment-Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
